import os

DATABASE_PATH = r"PUT WORK PC FILE PATH HERE"
if not os.path.exists(DATABASE_PATH):
    DATABASE_PATH_HOME_PC = r"PUT HOME PC FILE PATH HERE"

ALL_TRACKS_PATH = r"PUT ALL TRACKS FILE PATH HERE"

GUI_TITLE = r"CHOOSE YOUR TITLE"